#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# iterm2 shell_integration
test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh" || true

# nvm configuration
export NVM_DIR="$HOME/.nvm"
[ -s "/usr/local/opt/nvm/nvm.sh" ] && . "/usr/local/opt/nvm/nvm.sh"  # This loads nvm
[ -s "/usr/local/opt/nvm/etc/bash_completion.d/nvm" ] && . "/usr/local/opt/nvm/etc/bash_completion.d/nvm"  # This loads nvm bash_completion

# gcloud
# The next line updates PATH for the Google Cloud SDK.
if [ -f "$HOME/google-cloud-sdk/path.zsh.inc" ]; then . "$HOME/google-cloud-sdk/path.zsh.inc"; fi
# The next line enables shell command completion for gcloud.
if [ -f "$HOME/google-cloud-sdk/completion.zsh.inc" ]; then . "$HOME/google-cloud-sdk/completion.zsh.inc"; fi

# gh completion
eval "$(gh completion -s zsh)"


# fzf
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
export FZF_DEFAULT_OPTS='--height 40% --reverse --border'

# load functions
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/runcoms/functions/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/runcoms/functions/init.zsh"
fi

# load aliases
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/runcoms/alias.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/runcoms/alias.zsh"
fi


# local config 
# OS別の環境変数や公開したくないセキュリティ関連の情報はローカルファイルで管理するようにする
if [ -f ~/.zshrc.local ]; then
    source ~/.zshrc.local
fi
